server:
  port: 8083
  error:
    include-message: always
eureka:
  instance:
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/school_db
    platform: postgres
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
