server:
    port: 8084
    error:
        include-message: always
    
eureka:
    instance:
        preferIpAddress: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.17.0.2:5432/school_db
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    validationQuery:  SELECT 1
  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update 
